### ISSUE TITLE
About GPU and training time？

### ISSUE THREAD

**Issue by ShawnPi233** [CarlWangChina/SaMoye-SVC#2]
Thank you for your outstanding work. I would like to know on which graphics card your open-sourced 1700-hour data checkpoints were trained, and how long the training took?

**Comment by CarlWangChina** [comment]
It was trained on the A100, taking about a week. ---- Replied Message ----FromBingsong ***@***.***>Date12/10/2024 16:56 ***@***.***> ***@***.***>Subject[CarlWangChina/SaMoye-SVC] About GPU and training time？ (Issue #2)
Thank you for your outstanding work. I would like to know on which graphics card your open-sourced 1700-hour data checkpoints were trained, and how long the training took?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CarlWangChina/SaMoye-SVC/issues/2",
"url": "https://github.com/CarlWangChina/SaMoye-SVC/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
